# Generated by Django 5.1.2 on 2024-11-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='lugar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
